### ISSUE TITLE
On cover clcik

### ISSUE THREAD

**Issue by tushar-borole** [funkhousr/angular-coverflow#7]
Please add on cover click

**Comment by angelochen960** [comment]
how to pass coverId to click? I change the template to following, but it will never add the coverID to /goto
```
Cover.prototype.template = function(){
return '<a href="/goto/" + this.coverId><div class="coverflow-cover coverflow-cover-id-' + this.coverId + '"></div></a>';
}
```

**Comment by angelochen960** [comment]
try following, but it does not trigger the function in the ng-click:
```
Cover.prototype.template = function(){
	return '<a href ng-click="imageSelected()" class="coverflow-cover coverflow-cover-id-' + this.coverId + '"></a>';
};

```

**Comment by southdesign** [comment]
I'm currently a little short on time, sorry.

But might have to check where the click bubbles to. You could use something like https://chrome.google.com/webstore/category/apps?hl=en to find the right scope to catch the click.
